### ISSUE TITLE
Logic won't load the pre-built analyzer on OSX

### ISSUE THREAD

**Issue by jarkman** [lab11/MBusAnalzyer#3]
I've downloaded MBusAnalyzer/release/v0.4/mac/libMBusAnalyzer.dylib and set the Saleae preference to point to it.

With Logic 1.2.14, I now get a popup with "Unable to 'dlopen' so/dylib " when Logic starts, and I don't get an MBus analyzer in the list.

Any idea what might be up ? Thanks!

**Comment by ppannuto** [comment]
Hmm... I had Logic 1.2.12 locally, I just updated, and the existing fellow seems to work for both here :/

I just pushed (708e38a) a freshly built version to fix the displayed version string, maybe that'll fix your issue?

Failing that, I'd try building a copy yourself. It should be pretty easy, pull the saleae submodule and run `python build_analyzer.py` (the README has more verbose directions).

Can I ask what you're using MBus for? :)

**Comment by jarkman** [comment]
That fixed it, whatever it was. Many thanks!

This is for talking to a heat meter, part of a district-heating scheme. I have very little experience with MBus, just trying to make sense of what is going on.

Though I am not sure how to set up your analyzer for our setup - we have a serial port with Rx and Tx connected to some analogue hardware that interfaces to a 36v pair going to the heat meter. Our Salaea is connected to Rx and Tx, where we see packets being sent to and received from the heat meter.

The analyzer settings are asking for a CLK and a DAT, and we just don't have anything that might be the CLK. 

I suspect that means the analyzer just doesn't work for our situation - is that so ? 

Thanks,
Richard

**Comment by jarkman** [comment]
Oh - is this analyzer for MBus (http://www.m-bus.com/) or for MBus (http://mbus.io/) ? That might explain it!

**Comment by ppannuto** [comment]
Indeed, it is for the latter :)

**Comment by jarkman** [comment]
:-) Thanks for your help.
